#配置版本号
var: 1
debug: false
#自动重启
Auto_Restart: false
#达到指定危险值开始重启
MaxWaring: 25
#最小内存
minfree: 256M

#最小TPS
mintps: 8
#检测间隔 （单位 秒）
runTick: 1
#重启延时(单位 秒)
restartDeny: 15
#重启指令
onCommands:
  - "restart"

#更新Map文件加载时间,已方便清理过时地图
updateMapFileDate: false

#自动GC
AutoGC:
  Enable: false
  #最小危险值
  minWarin: 3
  #最小回收间隔
  minTick: 1H

#当储存空间不足时自动清理世界区域,多世界可选
AutoClearUpWorld:
  Enable: false
  #清理区域文件数量
  ClearNumber: 64
  MinFreeSpace: 64M
  #清理的世界和最后修改补偿天数(越大越不容易清理),如果区块最后访问距离当前时间（多少天前）小于数值也不会清理
  Worlds:
    world: 40
    zy: 0
    world_the_end: 10
    world_nether: 10

#防止区块实体堆积的数量 小于1关闭
EntityExplosion: 8848

#区块实体限制器
MaxEntity:
  Enable: false
  #用清理AI代替移除
  ClearAI: true
  Range: 32
  DefMaxEntity: 32
  Entitys:
    DROPPED_ITEM: 512
    ITEM_FRAME: 128
    ARMOR_STAND: 128
    VILLAGER: 30
    IRON_GOLEM: 16
    CHICKEN: 16
    PIG: 16
    COW: 16
    CAT: 16
    WOLF: 16
    SHEEP: 16
    TURTLE: 16
    BEE: 26
    DOLPHIN: 26
    ZOMBIE: 26
    PILLAGER: 26
    ARROW: 64
    BAT: 16
    SKELETON: 26
    CREEPER: 26
    ENDERMAN: 26
    