#配置版本号
var: 1
#最小内存（单位MB）
minfree: 256
#检测间隔 （单位 秒）
runTick: 25
#内存小于设定的值时执行
commands:
  - "say §b 服务器内存满啦,需要重启释放内存."
  - "say §b 服务器将在5秒后重启"
#延迟(单位 秒)
onTime: 5
#延迟执行指令
onCommands:
  - "kickall &f服务器需要重启释放内存,请等待30秒服务器重启完成后再加入服务器. 期待与您再见."
  - "restart"