name: MemFree
description: MemFree
main: cn.whiteg.memfree.MemFree
version: 1.0.1
api-version: '1.21'
author: MoeWhite
depend: []
softdepend: [Residence]
commands:
  memfree:
   description: MyPlug
   aliases: mf
  gc:
    description: System gc
#permissions:
#  MemFree.*:
#    description: MyplugPer
#    default: op
#    children:
#      MemFree.reload: true
#      MemFree.show: true
#  MemFree.reload:
#    description: Reload
#    default: op
#  MemFree.show:
#    description: Show
#    default: op
